export const COMMON_TECHNOLOGIES = [
    'React',
    'Next.js',
    'TypeScript',
    'Tailwind CSS',
    'Node.js',
    'Express',
    'Python',
    'Django',
    'MongoDB',
    'PostgreSQL',
    'Supabase',
    'Firebase',
    'Docker',
    'Kubernetes',
    'Git',
    'GraphQL',
    'REST API',
    'Vue.js',
    'Angular',
    'Svelte',
    'FastAPI',
    'Prisma',
    'SQLAlchemy',
    'Vercel',
    'Stripe',
    'Framer Motion',
    'Redux',
    'Socket.io',
    'React Native',
    'OpenAI',
    'Vercel AI SDK',
    'Storybook',
    'Figma',
  ] as const
  
  export type Technology = (typeof COMMON_TECHNOLOGIES)[number]
  