export const TECHNOLOGIES = [
  {
    type: 'FRONTEND',
    items: [
      'HTML',
      'JavaScript',
      'React',
      'NextJs',
      'GraphQL',
      'React Native',
      'Expo',
      'Zustand',
    ],
  },
  {
    type: 'STYLES',
    items: [
      'CSS',
      'Tailwind',
      'Bootstrap',
      'ShadCN',
      'Radix UI',
      'Material UI',
    ],
  },
  {
    type: 'BACKEND',
    items: [
      'Fastify',
      'NestJS',
      'Springboot',
      'PrismaORM',
      'TypeORM',
      'Hibernate',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'gRPC',
      'Microservices',
      'Swagger',
      'Supabase',
      'REST Api',
      'Websockets',
    ],
  },
  {
    type: 'OTHERS',
    items: [
      'Docker',
      'Stack AI',
      'Git',
      'Figma',
      'OpenAI',
      'Vercel',
      'Dokploy',
      'Resend',
      'Pusher',
    ],
  },
]
